version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database

